version: '3'

services:
  backend:
    image: chronikum/zfm-backend:alpha
    container_name: backend
    restart: unless-stopped
    environment:
      - DATABASE_PATH=mongodb://db:27017/backend
      - HOST=https://testing.de
      - HOST_API=https://irrturm.de/api
    ports:
      - "8080:8080"
    networks:
      - app-network
    command: ["npm","run-script","prod"]
  db:
    image: mongo
    container_name: db
    restart: unless-stopped
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
